namespace Motely.Enums;

internal enum InternalInvalid
{
    Invalid,
    NotImplemented,

    JokerExcludedByStream,
    PlanetExcludedByStream,
    TarotExcludedByStream,
    SpectralExcludedByStream,
    StandardCardExcludedByStream,
}

public enum MotelyItemType
{
    Mercury = MotelyItemTypeCategory.PlanetCard | MotelyPlanetCard.Mercury,
    Venus = MotelyItemTypeCategory.PlanetCard | MotelyPlanetCard.Venus,
    Earth = MotelyItemTypeCategory.PlanetCard | MotelyPlanetCard.Earth,
    Mars = MotelyItemTypeCategory.PlanetCard | MotelyPlanetCard.Mars,
    Jupiter = MotelyItemTypeCategory.PlanetCard | MotelyPlanetCard.Jupiter,
    Saturn = MotelyItemTypeCategory.PlanetCard | MotelyPlanetCard.Saturn,
    Uranus = MotelyItemTypeCategory.PlanetCard | MotelyPlanetCard.Uranus,
    Neptune = MotelyItemTypeCategory.PlanetCard | MotelyPlanetCard.Neptune,
    Pluto = MotelyItemTypeCategory.PlanetCard | MotelyPlanetCard.Pluto,
    PlanetX = MotelyItemTypeCategory.PlanetCard | MotelyPlanetCard.PlanetX,
    Ceres = MotelyItemTypeCategory.PlanetCard | MotelyPlanetCard.Ceres,
    Eris = MotelyItemTypeCategory.PlanetCard | MotelyPlanetCard.Eris,

    Familiar = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.Familiar,
    Grim = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.Grim,
    Incantation = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.Incantation,
    Talisman = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.Talisman,
    Aura = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.Aura,
    Wraith = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.Wraith,
    Sigil = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.Sigil,
    Ouija = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.Ouija,
    Ectoplasm = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.Ectoplasm,
    Immolate = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.Immolate,
    Ankh = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.Ankh,
    DejaVu = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.DejaVu,
    Hex = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.Hex,
    Trance = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.Trance,
    Medium = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.Medium,
    Cryptid = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.Cryptid,
    TheSoul = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.TheSoul,
    BlackHole = MotelyItemTypeCategory.SpectralCard | MotelySpectralCard.BlackHole,

    TheFool = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheFool,
    TheMagician = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheMagician,
    TheHighPriestess = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheHighPriestess,
    TheEmpress = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheEmpress,
    TheEmperor = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheEmperor,
    TheHierophant = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheHierophant,
    TheLovers = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheLovers,
    TheChariot = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheChariot,
    Justice = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.Justice,
    TheHermit = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheHermit,
    TheWheelOfFortune = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheWheelOfFortune,
    Strength = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.Strength,
    TheHangedMan = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheHangedMan,
    Death = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.Death,
    Temperance = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.Temperance,
    TheDevil = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheDevil,
    TheTower = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheTower,
    TheStar = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheStar,
    TheMoon = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheMoon,
    TheSun = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheSun,
    Judgement = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.Judgement,
    TheWorld = MotelyItemTypeCategory.TarotCard | MotelyTarotCard.TheWorld,

    TwoOfClubs = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.TwoOfClubs,
    ThreeOfClubs = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.ThreeOfClubs,
    FourOfClubs = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.FourOfClubs,
    FiveOfClubs = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.FiveOfClubs,
    SixOfClubs = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.SixOfClubs,
    SevenOfClubs = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.SevenOfClubs,
    EightOfClubs = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.EightOfClubs,
    NineOfClubs = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.NineOfClubs,
    TenOfClubs = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.TenOfClubs,
    JackOfClubs = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.JackOfClubs,
    QueenOfClubs = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.QueenOfClubs,
    KingOfClubs = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.KingOfClubs,
    AceOfClubs = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.AceOfClubs,

    TwoOfDiamonds = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.TwoOfDiamonds,
    ThreeOfDiamonds = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.ThreeOfDiamonds,
    FourOfDiamonds = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.FourOfDiamonds,
    FiveOfDiamonds = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.FiveOfDiamonds,
    SixOfDiamonds = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.SixOfDiamonds,
    SevenOfDiamonds = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.SevenOfDiamonds,
    EightOfDiamonds = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.EightOfDiamonds,
    NineOfDiamonds = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.NineOfDiamonds,
    TenOfDiamonds = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.TenOfDiamonds,
    JackOfDiamonds = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.JackOfDiamonds,
    QueenOfDiamonds = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.QueenOfDiamonds,
    KingOfDiamonds = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.KingOfDiamonds,
    AceOfDiamonds = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.AceOfDiamonds,

    TwoOfHearts = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.TwoOfHearts,
    ThreeOfHearts = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.ThreeOfHearts,
    FourOfHearts = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.FourOfHearts,
    FiveOfHearts = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.FiveOfHearts,
    SixOfHearts = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.SixOfHearts,
    SevenOfHearts = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.SevenOfHearts,
    EightOfHearts = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.EightOfHearts,
    NineOfHearts = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.NineOfHearts,
    TenOfHearts = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.TenOfHearts,
    JackOfHearts = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.JackOfHearts,
    QueenOfHearts = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.QueenOfHearts,
    KingOfHearts = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.KingOfHearts,
    AceOfHearts = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.AceOfHearts,

    TwoOfSpades = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.TwoOfSpades,
    ThreeOfSpades = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.ThreeOfSpades,
    FourOfSpades = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.FourOfSpades,
    FiveOfSpades = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.FiveOfSpades,
    SixOfSpades = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.SixOfSpades,
    SevenOfSpades = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.SevenOfSpades,
    EightOfSpades = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.EightOfSpades,
    NineOfSpades = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.NineOfSpades,
    TenOfSpades = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.TenOfSpades,
    JackOfSpades = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.JackOfSpades,
    QueenOfSpades = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.QueenOfSpades,
    KingOfSpades = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.KingOfSpades,
    AceOfSpades = MotelyItemTypeCategory.Standardcard | MotelyStandardCard.AceOfSpades,

    Joker = MotelyItemTypeCategory.Joker | MotelyJoker.Joker,
    GreedyJoker = MotelyItemTypeCategory.Joker | MotelyJoker.GreedyJoker,
    LustyJoker = MotelyItemTypeCategory.Joker | MotelyJoker.LustyJoker,
    WrathfulJoker = MotelyItemTypeCategory.Joker | MotelyJoker.WrathfulJoker,
    GluttonousJoker = MotelyItemTypeCategory.Joker | MotelyJoker.GluttonousJoker,
    JollyJoker = MotelyItemTypeCategory.Joker | MotelyJoker.JollyJoker,
    ZanyJoker = MotelyItemTypeCategory.Joker | MotelyJoker.ZanyJoker,
    MadJoker = MotelyItemTypeCategory.Joker | MotelyJoker.MadJoker,
    CrazyJoker = MotelyItemTypeCategory.Joker | MotelyJoker.CrazyJoker,
    DrollJoker = MotelyItemTypeCategory.Joker | MotelyJoker.DrollJoker,
    SlyJoker = MotelyItemTypeCategory.Joker | MotelyJoker.SlyJoker,
    WilyJoker = MotelyItemTypeCategory.Joker | MotelyJoker.WilyJoker,
    CleverJoker = MotelyItemTypeCategory.Joker | MotelyJoker.CleverJoker,
    DeviousJoker = MotelyItemTypeCategory.Joker | MotelyJoker.DeviousJoker,
    CraftyJoker = MotelyItemTypeCategory.Joker | MotelyJoker.CraftyJoker,
    HalfJoker = MotelyItemTypeCategory.Joker | MotelyJoker.HalfJoker,
    CreditCard = MotelyItemTypeCategory.Joker | MotelyJoker.CreditCard,
    Banner = MotelyItemTypeCategory.Joker | MotelyJoker.Banner,
    MysticSummit = MotelyItemTypeCategory.Joker | MotelyJoker.MysticSummit,
    EightBall = MotelyItemTypeCategory.Joker | MotelyJoker.EightBall,
    Misprint = MotelyItemTypeCategory.Joker | MotelyJoker.Misprint,
    RaisedFist = MotelyItemTypeCategory.Joker | MotelyJoker.RaisedFist,
    ChaostheClown = MotelyItemTypeCategory.Joker | MotelyJoker.ChaostheClown,
    ScaryFace = MotelyItemTypeCategory.Joker | MotelyJoker.ScaryFace,
    AbstractJoker = MotelyItemTypeCategory.Joker | MotelyJoker.AbstractJoker,
    DelayedGratification = MotelyItemTypeCategory.Joker | MotelyJoker.DelayedGratification,
    GrosMichel = MotelyItemTypeCategory.Joker | MotelyJoker.GrosMichel,
    EvenSteven = MotelyItemTypeCategory.Joker | MotelyJoker.EvenSteven,
    OddTodd = MotelyItemTypeCategory.Joker | MotelyJoker.OddTodd,
    Scholar = MotelyItemTypeCategory.Joker | MotelyJoker.Scholar,
    BusinessCard = MotelyItemTypeCategory.Joker | MotelyJoker.BusinessCard,
    Supernova = MotelyItemTypeCategory.Joker | MotelyJoker.Supernova,
    RideTheBus = MotelyItemTypeCategory.Joker | MotelyJoker.RideTheBus,
    Egg = MotelyItemTypeCategory.Joker | MotelyJoker.Egg,
    Runner = MotelyItemTypeCategory.Joker | MotelyJoker.Runner,
    IceCream = MotelyItemTypeCategory.Joker | MotelyJoker.IceCream,
    Splash = MotelyItemTypeCategory.Joker | MotelyJoker.Splash,
    BlueJoker = MotelyItemTypeCategory.Joker | MotelyJoker.BlueJoker,
    FacelessJoker = MotelyItemTypeCategory.Joker | MotelyJoker.FacelessJoker,
    GreenJoker = MotelyItemTypeCategory.Joker | MotelyJoker.GreenJoker,
    Superposition = MotelyItemTypeCategory.Joker | MotelyJoker.Superposition,
    ToDoList = MotelyItemTypeCategory.Joker | MotelyJoker.ToDoList,
    Cavendish = MotelyItemTypeCategory.Joker | MotelyJoker.Cavendish,
    RedCard = MotelyItemTypeCategory.Joker | MotelyJoker.RedCard,
    SquareJoker = MotelyItemTypeCategory.Joker | MotelyJoker.SquareJoker,
    RiffRaff = MotelyItemTypeCategory.Joker | MotelyJoker.RiffRaff,
    Photograph = MotelyItemTypeCategory.Joker | MotelyJoker.Photograph,
    ReservedParking = MotelyItemTypeCategory.Joker | MotelyJoker.ReservedParking,
    MailInRebate = MotelyItemTypeCategory.Joker | MotelyJoker.MailInRebate,
    Hallucination = MotelyItemTypeCategory.Joker | MotelyJoker.Hallucination,
    FortuneTeller = MotelyItemTypeCategory.Joker | MotelyJoker.FortuneTeller,
    Juggler = MotelyItemTypeCategory.Joker | MotelyJoker.Juggler,
    Drunkard = MotelyItemTypeCategory.Joker | MotelyJoker.Drunkard,
    GoldenJoker = MotelyItemTypeCategory.Joker | MotelyJoker.GoldenJoker,
    Popcorn = MotelyItemTypeCategory.Joker | MotelyJoker.Popcorn,
    WalkieTalkie = MotelyItemTypeCategory.Joker | MotelyJoker.WalkieTalkie,
    SmileyFace = MotelyItemTypeCategory.Joker | MotelyJoker.SmileyFace,
    GoldenTicket = MotelyItemTypeCategory.Joker | MotelyJoker.GoldenTicket,
    Swashbuckler = MotelyItemTypeCategory.Joker | MotelyJoker.Swashbuckler,
    HangingChad = MotelyItemTypeCategory.Joker | MotelyJoker.HangingChad,
    ShootTheMoon = MotelyItemTypeCategory.Joker | MotelyJoker.ShootTheMoon,

    JokerStencil = MotelyItemTypeCategory.Joker | MotelyJoker.JokerStencil,
    FourFingers = MotelyItemTypeCategory.Joker | MotelyJoker.FourFingers,
    Mime = MotelyItemTypeCategory.Joker | MotelyJoker.Mime,
    CeremonialDagger = MotelyItemTypeCategory.Joker | MotelyJoker.CeremonialDagger,
    MarbleJoker = MotelyItemTypeCategory.Joker | MotelyJoker.MarbleJoker,
    LoyaltyCard = MotelyItemTypeCategory.Joker | MotelyJoker.LoyaltyCard,
    Dusk = MotelyItemTypeCategory.Joker | MotelyJoker.Dusk,
    Fibonacci = MotelyItemTypeCategory.Joker | MotelyJoker.Fibonacci,
    SteelJoker = MotelyItemTypeCategory.Joker | MotelyJoker.SteelJoker,
    Hack = MotelyItemTypeCategory.Joker | MotelyJoker.Hack,
    Pareidolia = MotelyItemTypeCategory.Joker | MotelyJoker.Pareidolia,
    SpaceJoker = MotelyItemTypeCategory.Joker | MotelyJoker.SpaceJoker,
    Burglar = MotelyItemTypeCategory.Joker | MotelyJoker.Burglar,
    Blackboard = MotelyItemTypeCategory.Joker | MotelyJoker.Blackboard,
    SixthSense = MotelyItemTypeCategory.Joker | MotelyJoker.SixthSense,
    Constellation = MotelyItemTypeCategory.Joker | MotelyJoker.Constellation,
    Hiker = MotelyItemTypeCategory.Joker | MotelyJoker.Hiker,
    CardSharp = MotelyItemTypeCategory.Joker | MotelyJoker.CardSharp,
    Madness = MotelyItemTypeCategory.Joker | MotelyJoker.Madness,
    Seance = MotelyItemTypeCategory.Joker | MotelyJoker.Seance,
    Vampire = MotelyItemTypeCategory.Joker | MotelyJoker.Vampire,
    Shortcut = MotelyItemTypeCategory.Joker | MotelyJoker.Shortcut,
    Hologram = MotelyItemTypeCategory.Joker | MotelyJoker.Hologram,
    Cloud9 = MotelyItemTypeCategory.Joker | MotelyJoker.Cloud9,
    Rocket = MotelyItemTypeCategory.Joker | MotelyJoker.Rocket,
    MidasMask = MotelyItemTypeCategory.Joker | MotelyJoker.MidasMask,
    Luchador = MotelyItemTypeCategory.Joker | MotelyJoker.Luchador,
    GiftCard = MotelyItemTypeCategory.Joker | MotelyJoker.GiftCard,
    TurtleBean = MotelyItemTypeCategory.Joker | MotelyJoker.TurtleBean,
    Erosion = MotelyItemTypeCategory.Joker | MotelyJoker.Erosion,
    ToTheMoon = MotelyItemTypeCategory.Joker | MotelyJoker.ToTheMoon,
    StoneJoker = MotelyItemTypeCategory.Joker | MotelyJoker.StoneJoker,
    LuckyCat = MotelyItemTypeCategory.Joker | MotelyJoker.LuckyCat,
    Bull = MotelyItemTypeCategory.Joker | MotelyJoker.Bull,
    DietCola = MotelyItemTypeCategory.Joker | MotelyJoker.DietCola,
    TradingCard = MotelyItemTypeCategory.Joker | MotelyJoker.TradingCard,
    FlashCard = MotelyItemTypeCategory.Joker | MotelyJoker.FlashCard,
    SpareTrousers = MotelyItemTypeCategory.Joker | MotelyJoker.SpareTrousers,
    Ramen = MotelyItemTypeCategory.Joker | MotelyJoker.Ramen,
    Seltzer = MotelyItemTypeCategory.Joker | MotelyJoker.Seltzer,
    Castle = MotelyItemTypeCategory.Joker | MotelyJoker.Castle,
    MrBones = MotelyItemTypeCategory.Joker | MotelyJoker.MrBones,
    Acrobat = MotelyItemTypeCategory.Joker | MotelyJoker.Acrobat,
    SockAndBuskin = MotelyItemTypeCategory.Joker | MotelyJoker.SockAndBuskin,
    Troubadour = MotelyItemTypeCategory.Joker | MotelyJoker.Troubadour,
    Certificate = MotelyItemTypeCategory.Joker | MotelyJoker.Certificate,
    SmearedJoker = MotelyItemTypeCategory.Joker | MotelyJoker.SmearedJoker,
    Throwback = MotelyItemTypeCategory.Joker | MotelyJoker.Throwback,
    RoughGem = MotelyItemTypeCategory.Joker | MotelyJoker.RoughGem,
    Bloodstone = MotelyItemTypeCategory.Joker | MotelyJoker.Bloodstone,
    Arrowhead = MotelyItemTypeCategory.Joker | MotelyJoker.Arrowhead,
    OnyxAgate = MotelyItemTypeCategory.Joker | MotelyJoker.OnyxAgate,
    GlassJoker = MotelyItemTypeCategory.Joker | MotelyJoker.GlassJoker,
    Showman = MotelyItemTypeCategory.Joker | MotelyJoker.Showman,
    FlowerPot = MotelyItemTypeCategory.Joker | MotelyJoker.FlowerPot,
    MerryAndy = MotelyItemTypeCategory.Joker | MotelyJoker.MerryAndy,
    OopsAll6s = MotelyItemTypeCategory.Joker | MotelyJoker.OopsAll6s,
    TheIdol = MotelyItemTypeCategory.Joker | MotelyJoker.TheIdol,
    SeeingDouble = MotelyItemTypeCategory.Joker | MotelyJoker.SeeingDouble,
    Matador = MotelyItemTypeCategory.Joker | MotelyJoker.Matador,
    Satellite = MotelyItemTypeCategory.Joker | MotelyJoker.Satellite,
    Cartomancer = MotelyItemTypeCategory.Joker | MotelyJoker.Cartomancer,
    Astronomer = MotelyItemTypeCategory.Joker | MotelyJoker.Astronomer,
    Bootstraps = MotelyItemTypeCategory.Joker | MotelyJoker.Bootstraps,

    DNA = MotelyItemTypeCategory.Joker | MotelyJoker.DNA,
    Vagabond = MotelyItemTypeCategory.Joker | MotelyJoker.Vagabond,
    Baron = MotelyItemTypeCategory.Joker | MotelyJoker.Baron,
    Obelisk = MotelyItemTypeCategory.Joker | MotelyJoker.Obelisk,
    BaseballCard = MotelyItemTypeCategory.Joker | MotelyJoker.BaseballCard,
    AncientJoker = MotelyItemTypeCategory.Joker | MotelyJoker.AncientJoker,
    Campfire = MotelyItemTypeCategory.Joker | MotelyJoker.Campfire,
    Blueprint = MotelyItemTypeCategory.Joker | MotelyJoker.Blueprint,
    WeeJoker = MotelyItemTypeCategory.Joker | MotelyJoker.WeeJoker,
    HitTheRoad = MotelyItemTypeCategory.Joker | MotelyJoker.HitTheRoad,
    TheDuo = MotelyItemTypeCategory.Joker | MotelyJoker.TheDuo,
    TheTrio = MotelyItemTypeCategory.Joker | MotelyJoker.TheTrio,
    TheFamily = MotelyItemTypeCategory.Joker | MotelyJoker.TheFamily,
    TheOrder = MotelyItemTypeCategory.Joker | MotelyJoker.TheOrder,
    TheTribe = MotelyItemTypeCategory.Joker | MotelyJoker.TheTribe,
    Stuntman = MotelyItemTypeCategory.Joker | MotelyJoker.Stuntman,
    InvisibleJoker = MotelyItemTypeCategory.Joker | MotelyJoker.InvisibleJoker,
    Brainstorm = MotelyItemTypeCategory.Joker | MotelyJoker.Brainstorm,
    DriversLicense = MotelyItemTypeCategory.Joker | MotelyJoker.DriversLicense,
    BurntJoker = MotelyItemTypeCategory.Joker | MotelyJoker.BurntJoker,

    Canio = MotelyItemTypeCategory.Joker | MotelyJoker.Canio,
    Triboulet = MotelyItemTypeCategory.Joker | MotelyJoker.Triboulet,
    Yorick = MotelyItemTypeCategory.Joker | MotelyJoker.Yorick,
    Chicot = MotelyItemTypeCategory.Joker | MotelyJoker.Chicot,
    Perkeo = MotelyItemTypeCategory.Joker | MotelyJoker.Perkeo,

    Invalid = MotelyItemTypeCategory.Invalid | InternalInvalid.Invalid,
    NotImplemented = MotelyItemTypeCategory.Invalid | InternalInvalid.NotImplemented,
    JokerExcludedByStream = MotelyItemTypeCategory.Invalid | InternalInvalid.JokerExcludedByStream,
    PlanetExcludedByStream =
        MotelyItemTypeCategory.Invalid | InternalInvalid.PlanetExcludedByStream,
    TarotExcludedByStream = MotelyItemTypeCategory.Invalid | InternalInvalid.TarotExcludedByStream,
    SpectralExcludedByStream =
        MotelyItemTypeCategory.Invalid | InternalInvalid.SpectralExcludedByStream,
    StandardCardExcludedByStream =
        MotelyItemTypeCategory.Invalid | InternalInvalid.StandardCardExcludedByStream,
}
