// Generates the API section of Motely.Wasm/README.md from the built typings, between
// <!-- api:start --> and <!-- api:end -->. Prose outside the markers is never touched.
//
//   node scripts/readme-gen.mjs                      rewrite the block in README.md
//   node scripts/readme-gen.mjs --check              exit 1 if the block is stale (prepublishOnly)
//   node scripts/readme-gen.mjs --typings <path>     typings to read (default: bin/motely-wasm/generated/modules/index.g.d.mts)
//   node scripts/readme-gen.mjs --readme <path>      README to update (default: Motely.Wasm/README.md)
//   node scripts/readme-gen.mjs --print              write the generated block to stdout instead
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join, resolve, relative, dirname } from "node:path";
import { parseSurface, defaultTypings, wasmDir } from "./api-surface.mjs";

const START = "<!-- api:start -->";
const END = "<!-- api:end -->";
const MAX_ENUM_VALUES = 16;

function arg(name) {
    const i = process.argv.indexOf(name);
    return i >= 0 ? process.argv[i + 1] : undefined;
}
const has = (name) => process.argv.includes(name);

const code = (s) => "`" + s.replace(/\|/g, "\\|") + "`";

function table(headers, rows) {
    return [`| ${headers.join(" | ")} |`, `|${headers.map(() => "---").join("|")}|`, ...rows.map((r) => `| ${r.join(" | ")} |`)].join("\n");
}

/** bcl re-exports next to the generated typings: bin/motely-wasm/bcl/index.d.mts. */
function bclModules(typingsPath) {
    const bcl = join(dirname(typingsPath), "..", "..", "bcl", "index.d.mts");
    if (!existsSync(bcl)) return [];
    return [...readFileSync(bcl, "utf8").matchAll(/export \* from "\.\/(\w+)\.mjs"/g)].map((m) => m[1]);
}

export function renderApi(surface, typingsPath) {
    const out = [START, "", "<!-- generated by scripts/readme-gen.mjs from the built typings; edit the C# [Export]s, then `npm run readme:gen` -->", ""];

    out.push("### Namespaces", "");
    for (const [ns, def] of Object.entries(surface.namespaces)) {
        out.push(`#### \`${ns}\``, "");
        const rows = Object.entries(def.members).map(([name, m]) => {
            const kind = m.kind === "const" && m.sig.includes("Event<") ? "event" : m.kind === "let" ? "import (JS binds)" : m.kind;
            return [code(`${ns}.${name}`), kind, code(m.sig)];
        });
        out.push(table(["member", "kind", "signature"], rows), "");
    }

    const interfaces = Object.entries(surface.interfaces);
    if (interfaces.length) {
        out.push("### Interfaces", "");
        for (const [name, def] of interfaces) {
            out.push(`#### \`${name}\``, "");
            const rows = Object.entries(def.members).map(([member, m]) => [code(member), m.kind, code(m.sig)]);
            out.push(table(["member", "kind", "signature"], rows), "");
        }
    }

    const classes = Object.entries(surface.classes);
    if (classes.length) {
        out.push("### Classes", "");
        for (const [name, def] of classes) {
            out.push(`#### \`${name}\``, "");
            out.push(table(["member", "kind", "signature"], Object.entries(def.members).map(([member, m]) => [code(member), m.kind, code(m.sig)])), "");
        }
    }

    const fns = Object.entries(surface.functions);
    if (fns.length) {
        out.push("### Top-level exports", "");
        out.push(table(["name", "kind", "signature"], fns.map(([name, m]) => [code(name), m.kind, code(m.sig)])), "");
    }

    const enums = Object.entries(surface.enums);
    if (enums.length) {
        out.push("### Enums", "");
        const rows = enums.map(([name, values]) => [
            code(name),
            String(values.length),
            values.length <= MAX_ENUM_VALUES ? values.map(code).join(", ") : `${values.slice(0, 5).map(code).join(", ")}, … (${values.length} values)`,
        ]);
        out.push(table(["enum", "values", "members"], rows), "");
    }

    const types = Object.entries(surface.types);
    if (types.length) {
        out.push("### Types", "");
        const rows = types.map(([name, def]) => [
            code(name),
            def.alias !== undefined ? code(`= ${def.alias}`) : def.fields.length ? def.fields.map(code).join(", ") : "_opaque handle_",
        ]);
        out.push(table(["type", "shape"], rows), "");
    }

    const bcl = bclModules(typingsPath);
    if (bcl.length) out.push(`### \`motely-wasm/bcl\``, "", `Bootsharp BCL re-exports: ${bcl.map(code).join(", ")}.`, "");

    out.push(END);
    return out.join("\n");
}

export function splice(readme, block) {
    const s = readme.indexOf(START);
    const e = readme.indexOf(END);
    if (s < 0 || e < 0 || e < s) throw new Error(`README has no ${START} … ${END} markers`);
    return readme.slice(0, s) + block + readme.slice(e + END.length);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
    const typingsPath = resolve(arg("--typings") ?? defaultTypings);
    const readmePath = resolve(arg("--readme") ?? join(wasmDir, "README.md"));
    if (!existsSync(typingsPath)) {
        console.error(`readme-gen: ${typingsPath} not found. Run \`npm run build\` first.`);
        process.exit(1);
    }
    const surface = parseSurface(readFileSync(typingsPath, "utf8"));
    const block = renderApi(surface, typingsPath);
    if (has("--print")) {
        process.stdout.write(block + "\n");
        process.exit(0);
    }
    const readme = readFileSync(readmePath, "utf8");
    const next = splice(readme, block);
    const label = relative(process.cwd(), readmePath) || readmePath;
    if (has("--check")) {
        if (next === readme) {
            console.log(`readme-gen: ${label} API block is current`);
            process.exit(0);
        }
        const before = readme.slice(readme.indexOf(START), readme.indexOf(END) + END.length).split("\n");
        const after = block.split("\n");
        const gone = before.filter((l) => !after.includes(l));
        const fresh = after.filter((l) => !before.includes(l));
        console.error(`readme-gen: ${label} API block is STALE against ${relative(process.cwd(), typingsPath)}. Run \`npm run readme:gen\`.`);
        for (const l of gone) console.error(`  - ${l}`);
        for (const l of fresh) console.error(`  + ${l}`);
        process.exit(1);
    }
    if (next === readme) console.log(`readme-gen: ${label} already current`);
    else {
        writeFileSync(readmePath, next);
        console.log(`readme-gen: rewrote the API block in ${label}`);
    }
}
