<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateProgramFile>false</GenerateProgramFile>
    <IsPackable>false</IsPackable>
    <RunSettingsFilePath>../coverage.runsettings</RunSettingsFilePath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Motely/Motely.csproj" />
    <ProjectReference Include="../Motely.DataLake/Motely.DataLake.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Verify.Xunit" />
    <PackageReference Include="Verify.DiffPlex" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Motely.Enums" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="JimmolateScoringOrderTests.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="AppHostModelTests.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Update="seeds/*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="JamlFilters/**/*.jaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
