<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Optimize>true</Optimize>
    <TieredCompilation>true</TieredCompilation>
    <TieredPGO>true</TieredPGO>
    <TieredCompilationQuickJit>false</TieredCompilationQuickJit>
    <TieredCompilationQuickJitForLoops>false</TieredCompilationQuickJitForLoops>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <EnableHardwareIntrinsics>true</EnableHardwareIntrinsics>
    <EnableAVX2>true</EnableAVX2>
    <EnableAVX512F>true</EnableAVX512F>
    <EnableAVX512BW>true</EnableAVX512BW>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>MotelyWorker</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot Condition="'$(RuntimeIdentifier)' != 'browser-wasm' and '$(DesignTimeBuild)' != 'true'">true</PublishAot>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <ProjectReference Include="..\Motely\Motely.csproj" />
    <ProjectReference Include="..\Motely.DataLake\Motely.DataLake.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <SuppressAotAnalysisWarnings>true</SuppressAotAnalysisWarnings>
  </PropertyGroup>
</Project>
