<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPublishable>false</IsPublishable>
    <PublishReadyToRun>false</PublishReadyToRun>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateProgramFile>false</GenerateProgramFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Version>$(MotelyVersion)</Version>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <!-- Packages (versions from Directory.Packages.props) -->
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="VYaml" />
    <PackageReference Include="VYaml.Annotations" />
  </ItemGroup>
</Project>
