using System.Globalization;
using System.Net;
using System.Text;
using Motely.Enums;

namespace Motely.JsonRender;

public static class HtmlReportRenderer
{
    private static string E(string? s) => WebUtility.HtmlEncode(s ?? string.Empty);

    public static string Render(RenderReport report)
    {
        var sb = new StringBuilder(64 * 1024);
        string title = report.Filter.Name ?? report.Filter.Id;
        string generated = report.GeneratedAt.ToString(
            "yyyy-MM-dd HH:mm:ss 'UTC'",
            CultureInfo.InvariantCulture
        );

        sb.Append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n");
        sb.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
        sb.Append("<title>").Append(E(title)).Append(" — Motely seed analysis</title>\n");
        sb.Append("<style>\n").Append(Css).Append("\n</style>\n</head>\n<body>\n");

        sb.Append("<header class=\"report-header\">\n");
        sb.Append("  <h1>").Append(E(title)).Append("</h1>\n");
        if (report.Filter.Description is { Length: > 0 } desc)
            sb.Append("  <p class=\"desc\">").Append(E(desc)).Append("</p>\n");
        sb.Append("  <p class=\"meta\">")
            .Append("Deck <strong>").Append(E(report.Deck.ToString())).Append("</strong>")
            .Append(" · Stake <strong>").Append(E(report.Stake.ToString())).Append("</strong>")
            .Append(" · <strong>").Append(report.Seeds.Count).Append("</strong> seed(s)")
            .Append(" · <strong>").Append(report.EventRolls).Append("</strong> event rolls per seed")
            .Append(" · generated ").Append(E(generated));
        if (report.Filter.Author is { Length: > 0 } author)
            sb.Append(" · filter by ").Append(E(author));
        sb.Append("</p>\n</header>\n<main>\n");

        for (int i = 0; i < report.Seeds.Count; i++)
            RenderSeed(sb, report.Seeds[i], open: i == 0);

        sb.Append("</main>\n<footer class=\"report-footer\">Generated by Motely.JsonRender from MotelyJamlyzer results.")
            .Append("</footer>\n</body>\n</html>\n");
        return sb.ToString();
    }

    private static void RenderSeed(StringBuilder sb, RenderSeed seed, bool open)
    {
        sb.Append("<details class=\"seed\"").Append(open ? " open" : "").Append(">\n");
        sb.Append("  <summary>")
            .Append("<span class=\"seed-name\">").Append(E(seed.Seed)).Append("</span>")
            .Append("<span class=\"seed-score\">score ").Append(seed.Score).Append("</span>")
            .Append("<span class=\"seed-meta\">").Append(seed.Antes.Count).Append(" antes</span>")
            .Append("</summary>\n");

        foreach (var ante in seed.Antes)
            RenderAnte(sb, ante);

        if (seed.ErraticDeck is { Count: > 0 } erratic)
        {
            sb.Append("  <details class=\"secondary\"><summary>Erratic deck (")
                .Append(erratic.Count).Append(" cards)</summary>\n    <div class=\"card-row\">");
            foreach (var item in erratic)
                RenderCard(sb, item);
            sb.Append("</div>\n  </details>\n");
        }

        RenderEvents(sb, seed);
        sb.Append("</details>\n");
    }

    private static void RenderAnte(StringBuilder sb, RenderAnte ante)
    {
        sb.Append("  <section class=\"ante\">\n");
        sb.Append("    <h3>Ante ").Append(ante.Ante)
            .Append(" <span class=\"ante-sub\">Boss: ").Append(E(FormatUtils.FormatBoss(ante.Boss)))
            .Append(" · Voucher: ").Append(E(FormatUtils.FormatVoucher(ante.Voucher)))
            .Append("</span></h3>\n");
        sb.Append("    <div class=\"ante-grid\">\n");

        sb.Append("      <div class=\"group\"><h4>Boss Blind</h4>");
        RenderChip(sb, "chip-boss", "BOSS", FormatUtils.FormatBoss(ante.Boss));
        sb.Append("</div>\n");

        sb.Append("      <div class=\"group\"><h4>Voucher</h4>");
        RenderChip(sb, "chip-voucher", "VOUCHER", FormatUtils.FormatVoucher(ante.Voucher));
        sb.Append("</div>\n");

        sb.Append("      <div class=\"group\"><h4>Tags</h4>");
        RenderChip(sb, "chip-tag", "SMALL BLIND TAG", FormatUtils.FormatTag(ante.SmallBlindTag));
        RenderChip(sb, "chip-tag", "BIG BLIND TAG", FormatUtils.FormatTag(ante.BigBlindTag));
        sb.Append("</div>\n");

        sb.Append("      <div class=\"group group-wide\"><h4>Shop (")
            .Append(ante.ShopItems.Count).Append(" items)</h4>\n        <div class=\"card-row\">");
        foreach (var item in ante.ShopItems)
            RenderCard(sb, item);
        sb.Append("</div>\n      </div>\n");

        sb.Append("      <div class=\"group group-wide\"><h4>Packs (")
            .Append(ante.Packs.Count).Append(")</h4>\n        <div class=\"pack-row\">");
        foreach (var pack in ante.Packs)
        {
            sb.Append("<div class=\"pack\"><div class=\"pack-title\">")
                .Append(E(FormatUtils.FormatPackName(pack.Pack)))
                .Append("</div><div class=\"card-row\">");
            foreach (var item in pack.Items)
                RenderCard(sb, item);
            sb.Append("</div></div>");
        }
        sb.Append("\n        </div>\n      </div>\n");

        sb.Append("    </div>\n");
        RenderStreams(sb, ante);
        sb.Append("  </section>\n");
    }

    private static void RenderChip(StringBuilder sb, string cssClass, string kind, string name)
    {
        sb.Append("<div class=\"chip ").Append(cssClass).Append("\">")
            .Append("<span class=\"chip-kind\">").Append(kind).Append("</span>")
            .Append("<span class=\"chip-name\">").Append(E(name)).Append("</span></div>");
    }

    private static void RenderCard(StringBuilder sb, RenderItem item)
    {
        bool isStandardCard = item.TypeCategory == MotelyItemTypeCategory.Standardcard;
        string categoryClass = item.TypeCategory switch
        {
            MotelyItemTypeCategory.Joker => "cat-joker",
            MotelyItemTypeCategory.TarotCard => "cat-tarot",
            MotelyItemTypeCategory.PlanetCard => "cat-planet",
            MotelyItemTypeCategory.SpectralCard => "cat-spectral",
            MotelyItemTypeCategory.Standardcard => "cat-card suit-" + item.Suit!.ToLowerInvariant(),
            _ => "cat-other",
        };
        string editionClass = item.Edition switch
        {
            MotelyItemEdition.Foil => " ed-foil",
            MotelyItemEdition.Holographic => " ed-holographic",
            MotelyItemEdition.Polychrome => " ed-polychrome",
            MotelyItemEdition.Negative => " ed-negative",
            _ => "",
        };

        sb.Append("<div class=\"card ").Append(categoryClass).Append(editionClass).Append("\">");
        sb.Append("<span class=\"card-cat\">").Append(E(CategoryLabel(item.TypeCategory))).Append("</span>");
        if (isStandardCard)
        {
            sb.Append("<span class=\"card-rank\">").Append(E(ShortRank(item.Rank!))).Append("</span>");
            sb.Append("<span class=\"card-suit\">").Append(E(item.Suit)).Append("</span>");
        }
        else
        {
            sb.Append("<span class=\"card-name\">")
                .Append(E(FormatUtils.FormatDisplayName(item.Type.ToString())))
                .Append("</span>");
        }

        if (item.Enhancement != MotelyItemEnhancement.None)
            RenderBadge(sb, "badge-enh", item.Enhancement.ToString());
        if (item.Edition != MotelyItemEdition.None)
            RenderBadge(sb, "badge-ed", item.Edition.ToString());
        if (item.Seal != MotelyItemSeal.None)
        {
            sb.Append("<span class=\"seal\"><span class=\"seal-dot seal-")
                .Append(item.Seal.ToString().ToLowerInvariant())
                .Append("\"></span>").Append(E(item.Seal.ToString())).Append(" seal</span>");
        }
        foreach (var sticker in item.Stickers)
            RenderBadge(sb, "badge-sticker", sticker);
        sb.Append("</div>");
    }

    private static void RenderBadge(StringBuilder sb, string cssClass, string text) =>
        sb.Append("<span class=\"badge ").Append(cssClass).Append("\">").Append(E(text)).Append("</span>");

    private static string CategoryLabel(MotelyItemTypeCategory category) =>
        category switch
        {
            MotelyItemTypeCategory.Joker => "JOKER",
            MotelyItemTypeCategory.TarotCard => "TAROT",
            MotelyItemTypeCategory.PlanetCard => "PLANET",
            MotelyItemTypeCategory.SpectralCard => "SPECTRAL",
            MotelyItemTypeCategory.Standardcard => "CARD",
            _ => "ITEM",
        };

    private static string ShortRank(string rank) =>
        rank switch
        {
            "Two" => "2",
            "Three" => "3",
            "Four" => "4",
            "Five" => "5",
            "Six" => "6",
            "Seven" => "7",
            "Eight" => "8",
            "Nine" => "9",
            "Ten" => "10",
            "Jack" => "J",
            "Queen" => "Q",
            "King" => "K",
            "Ace" => "A",
            _ => rank,
        };

    private static void RenderStreams(StringBuilder sb, RenderAnte ante)
    {
        sb.Append("    <details class=\"secondary\"><summary>Pulls &amp; shop streams (raw rolls)</summary>\n");
        RenderItemRow(sb, "Judgement jokers", ante.Pulls.JudgementJokers);
        RenderItemRow(sb, "Wraith jokers", ante.Pulls.WraithJokers);
        RenderItemRow(sb, "Emperor tarots", ante.Pulls.EmperorTarots);
        RenderItemRow(sb, "Purple-seal tarots", ante.Pulls.PurpleSealTarots);
        RenderItemRow(sb, "Sixth Sense spectrals", ante.Pulls.SixthSenseSpectrals);
        RenderItemRow(sb, "Séance spectrals", ante.Pulls.SeanceSpectrals);
        RenderItemRow(sb, "Riff-Raff jokers", ante.Pulls.RiffRaffJokers);
        RenderItemRow(sb, "Rare-tag jokers", ante.Pulls.RareTagJokers);
        RenderItemRow(sb, "Uncommon-tag jokers", ante.Pulls.UncommonTagJokers);
        RenderItemRow(sb, "Legendary jokers", ante.Pulls.LegendaryJokers);
        sb.Append("      <div class=\"row\"><span class=\"row-label\">Voucher sequence</span><span class=\"row-items\">")
            .Append(E(string.Join(", ", ante.Pulls.VoucherSequence.Take(12).Select(FormatUtils.FormatVoucher))))
            .Append(ante.Pulls.VoucherSequence.Count > 12 ? $" (+{ante.Pulls.VoucherSequence.Count - 12} more)" : "")
            .Append("</span></div>\n");
        RenderItemRow(sb, "Shop jokers", ante.ShopStreams.ShopJokers);
        RenderItemRow(sb, "Shop jokers (common)", ante.ShopStreams.CommonShopJokers);
        RenderItemRow(sb, "Shop jokers (uncommon)", ante.ShopStreams.UncommonShopJokers);
        RenderItemRow(sb, "Shop jokers (rare)", ante.ShopStreams.RareShopJokers);
        RenderItemRow(sb, "Shop tarots", ante.ShopStreams.ShopTarots);
        RenderItemRow(sb, "Shop planets", ante.ShopStreams.ShopPlanets);
        RenderItemRow(sb, "Shop spectrals", ante.ShopStreams.ShopSpectrals);
        sb.Append("    </details>\n");
    }

    private static void RenderItemRow(StringBuilder sb, string label, IReadOnlyList<RenderItem> items)
    {
        const int cap = 12;
        sb.Append("      <div class=\"row\"><span class=\"row-label\">").Append(E(label)).Append("</span><span class=\"row-items\">");
        sb.Append(E(string.Join(", ", items.Take(cap).Select(i => i.Name))));
        if (items.Count > cap)
            sb.Append(" (+").Append(items.Count - cap).Append(" more)");
        sb.Append("</span></div>\n");
    }

    private static void RenderEvents(StringBuilder sb, RenderSeed seed)
    {
        var ev = seed.Events;
        sb.Append("  <details class=\"secondary\"><summary>Events &amp; stream state</summary>\n");
        RenderBoolRow(sb, "Lucky Money triggers", ev.LuckyMoney);
        RenderBoolRow(sb, "Lucky Mult triggers", ev.LuckyMult);
        RenderBoolRow(sb, "Cavendish survives", ev.Cavendish);
        RenderBoolRow(sb, "Gros Michel survives", ev.GrosMichel);
        RenderBoolRow(sb, "Space Joker upgrades", ev.Space);
        RenderBoolRow(sb, "Business Joker faces", ev.Business);
        RenderBoolRow(sb, "Bloodstone procs", ev.Bloodstone);
        RenderBoolRow(sb, "Parking procs", ev.Parking);
        RenderBoolRow(sb, "8 Ball procs", ev.EightBall);
        RenderBoolRow(sb, "Glass breaks", ev.Glass);
        RenderBoolRow(sb, "Omen Globe procs", ev.OmenGlobe);
        RenderBoolRow(sb, "The Wheel hits", ev.TheWheel);

        var editions = ev.WheelOfFortune
            .Where(e => e != MotelyItemEdition.None)
            .GroupBy(e => e)
            .Select(g => $"{FormatUtils.FormatDisplayName(g.Key.ToString())} ×{g.Count()}");
        sb.Append("    <div class=\"row\"><span class=\"row-label\">Wheel of Fortune editions</span><span class=\"row-items\">")
            .Append(E(editions.Any() ? string.Join(", ", editions) : "none in this window"))
            .Append("</span></div>\n");

        sb.Append("    <div class=\"row\"><span class=\"row-label\">Misprint values</span><span class=\"row-items\">")
            .Append(
                ev.Misprint.Length > 0
                    ? $"min {ev.Misprint.Min()}, max {ev.Misprint.Max()} across {ev.Misprint.Length} rolls"
                    : "none in this window"
            )
            .Append("</span></div>\n");

        sb.Append("    <div class=\"row\"><span class=\"row-label\">Stream resume offset</span><span class=\"row-items\">")
            .Append(seed.StreamStates.RollOffset).Append(" rolls consumed</span></div>\n");
        sb.Append("  </details>\n");
    }

    private static void RenderBoolRow(StringBuilder sb, string label, bool[] hits) =>
        sb.Append("    <div class=\"row\"><span class=\"row-label\">").Append(E(label))
            .Append("</span><span class=\"row-items\">").Append(hits.Count(h => h))
            .Append(" of ").Append(hits.Length).Append(" rolls</span></div>\n");

    private const string Css = """
        :root {
          --bg: #232A34;
          --panel: #37424D;
          --panel-2: #2D3640;
          --blue: #4287F5;
          --red: #FF5F5F;
          --green: #4CA064;
          --purple: #7D60E0;
          --orange: #FFA500;
          --teal: #37B8B2;
          --gold: #E7C25A;
          --text: #E8ECF2;
          --muted: #A9B2BD;
        }
        * { box-sizing: border-box; }
        body {
          margin: 0; padding: 24px;
          background: var(--bg); color: var(--text);
          font-family: "Segoe UI", system-ui, -apple-system, sans-serif;
          line-height: 1.45;
        }
        main { max-width: 1200px; margin: 0 auto; }

        /* Header — the run at a glance */
        .report-header {
          max-width: 1200px; margin: 0 auto 16px;
          background: var(--panel); border-radius: 10px; padding: 16px 20px;
          border-left: 6px solid var(--blue);
        }
        .report-header h1 { margin: 0 0 6px; font-size: 1.5rem; }
        .report-header .desc { margin: 0 0 8px; color: var(--text); max-width: 80ch; }
        .report-header .meta { margin: 0; color: var(--muted); font-size: .9rem; }
        .report-footer { max-width: 1200px; margin: 24px auto 0; color: var(--muted); font-size: .8rem; }

        /* Seed sections collapse so a multi-seed run stays navigable */
        details.seed {
          background: var(--panel); border-radius: 10px; margin: 0 0 14px; padding: 0;
          border: 1px solid #46525F;
        }
        details.seed > summary {
          cursor: pointer; padding: 14px 18px; list-style: none;
          display: flex; align-items: baseline; gap: 14px; flex-wrap: wrap;
        }
        details.seed > summary::before { content: "▸ "; color: var(--muted); }
        details.seed[open] > summary::before { content: "▾ "; }
        .seed-name { font-size: 1.3rem; font-weight: 700; letter-spacing: .06em; }
        .seed-score {
          background: var(--green); color: #0E1318; font-weight: 700;
          border-radius: 6px; padding: 2px 10px; font-size: .85rem;
        }
        .seed-meta { color: var(--muted); font-size: .85rem; }

        /* One panel per ante */
        .ante {
          background: var(--panel-2); border-radius: 8px; margin: 0 14px 14px; padding: 12px 16px;
          border-top: 3px solid var(--orange);
        }
        .ante h3 { margin: 0 0 10px; font-size: 1.05rem; }
        .ante-sub { color: var(--muted); font-weight: 400; font-size: .85rem; }
        .ante-grid { display: flex; flex-wrap: wrap; gap: 14px; }
        .group { min-width: 150px; }
        .group-wide { flex: 1 1 100%; }
        .group h4 {
          margin: 0 0 6px; font-size: .72rem; text-transform: uppercase;
          letter-spacing: .09em; color: var(--muted);
        }

        /* Boss / voucher / tag chips — the kind label is text, color is the accent */
        .chip {
          display: inline-flex; flex-direction: column; align-items: flex-start;
          border-radius: 8px; padding: 6px 12px; margin: 0 6px 6px 0;
          border-left: 5px solid; background: var(--panel);
        }
        .chip-kind { font-size: .62rem; letter-spacing: .1em; color: var(--muted); }
        .chip-name { font-weight: 600; font-size: .92rem; }
        .chip-boss { border-color: var(--red); }
        .chip-voucher { border-color: var(--green); }
        .chip-tag { border-color: var(--gold); }

        /* Card chips — rounded mini-cards in a row, like Balatro's shop slots */
        .card-row { display: flex; flex-wrap: wrap; gap: 6px; }
        .card {
          display: inline-flex; flex-direction: column; align-items: center; justify-content: center;
          width: 60px; min-height: 80px; border-radius: 8px; padding: 5px 3px;
          border: 2px solid var(--muted); background: var(--panel);
          text-align: center; gap: 2px;
        }
        .card-cat { font-size: .55rem; letter-spacing: .08em; color: var(--muted); }
        .card-name { font-size: .68rem; font-weight: 600; line-height: 1.15; }
        .card-rank { font-size: 1.15rem; font-weight: 800; line-height: 1; }
        .card-suit { font-size: .62rem; font-weight: 600; }

        /* Category accents — each chip also prints its category as text above the name */
        .cat-joker { border-color: var(--red); }
        .cat-tarot { border-color: var(--purple); }
        .cat-planet { border-color: var(--blue); }
        .cat-spectral { border-color: var(--teal); }
        .suit-hearts { border-color: var(--red); }    .suit-hearts .card-rank { color: var(--red); }
        .suit-diamonds { border-color: var(--orange); } .suit-diamonds .card-rank { color: var(--orange); }
        .suit-clubs { border-color: var(--green); }    .suit-clubs .card-rank { color: var(--green); }
        .suit-spades { border-color: var(--blue); }    .suit-spades .card-rank { color: var(--blue); }

        /* Editions — gradient treatments plus a text badge that names the edition */
        .ed-foil {
          background: linear-gradient(135deg, rgba(190,205,225,.38), rgba(120,150,190,.14) 45%, rgba(190,205,225,.32)), var(--panel);
          box-shadow: inset 0 0 0 1px #B9C6D9;
        }
        .ed-holographic {
          border-color: transparent;
          background:
            linear-gradient(var(--panel), var(--panel)) padding-box,
            linear-gradient(135deg, #FF5F5F, #FFA500, #E7C25A, #4CA064, #4287F5, #7D60E0) border-box;
        }
        .ed-polychrome {
          border-color: transparent;
          background:
            linear-gradient(var(--panel), var(--panel)) padding-box,
            linear-gradient(135deg, #FF5F5F, #E8ECF2, #4287F5) border-box;
        }
        .ed-negative {
          background: #0E1318; color: #D9E6FF; border-color: var(--purple);
          box-shadow: 0 0 10px 2px rgba(125,96,224,.65);
        }

        /* Badges and seals — text first, color as backup */
        .badge { font-size: .55rem; font-weight: 700; border-radius: 4px; padding: 1px 4px; }
        .badge-ed { background: var(--purple); color: #fff; }
        .badge-enh { background: var(--blue); color: #fff; }
        .badge-sticker { background: var(--gold); color: #232A34; }
        .seal { display: inline-flex; align-items: center; gap: 3px; font-size: .55rem; color: var(--text); }
        .seal-dot { width: 8px; height: 8px; border-radius: 50%; display: inline-block; }
        .seal-gold { background: var(--gold); }
        .seal-red { background: var(--red); }
        .seal-blue { background: var(--blue); }
        .seal-purple { background: var(--purple); }

        /* Booster packs — bordered groups holding their own card rows */
        .pack-row { display: flex; flex-wrap: wrap; gap: 10px; }
        .pack {
          border: 1px dashed var(--orange); border-radius: 8px; padding: 8px;
          background: rgba(255,165,0,.06);
        }
        .pack-title {
          font-size: .72rem; font-weight: 700; color: var(--orange);
          margin-bottom: 6px; text-transform: uppercase; letter-spacing: .06em;
        }

        /* Secondary sections — raw streams and events, collapsed by default */
        details.secondary { margin: 4px 14px 14px; font-size: .85rem; }
        .ante details.secondary { margin: 10px 0 0; }
        details.secondary > summary { cursor: pointer; color: var(--muted); padding: 4px 0; }
        .row { display: flex; gap: 10px; padding: 2px 0; }
        .row-label { flex: 0 0 200px; color: var(--muted); }
        .row-items { flex: 1; }
        """;
}
